language: "ja-JP"
early_access: false
enable_free_tier: true
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  fail_commit_status: true
  collapse_walkthrough: false
  auto_apply_labels: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["main", "develop"]
chat:
  auto_reply: true
